# Use an official Java parent image
FROM openjdk:11-jdk-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file generated by your build tool (Maven or Gradle) into the container
COPY target/*.jar app.jar

# Expose the application's port
EXPOSE 5000

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]